명목형 데이터에 대한 개념 계층 생성  
https://hongjinhyeon.tistory.com/110

범주형 데이터 분석  
https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=kimjungg&logNo=221238887930

### 【범주형 변수처리】

### 변수 
기계학습에서는  column = feature = dimension = variable을 혼용해서 사용한다.  

1 범주형 변수(Categorical Data)=질적변수(Qualitative Variable) : 몇개의 범주로 나누어진 자료를 의미
 - 명목형(Nominal Data): 성별, 성공여부, 혈액형 등 순서를 매길 수 없고 셀수 있다는 특징이 있다.
 - 순서형(Ordinal Data) : 교육수준, 만족도등  그들 사이에 순서 관계가 존재하는 자료

2 수치형 변수 : 이산형과 연속형으로 이루어진 자료를 의미
  - 이산형(Discrete Data) :출산횟수, 불량품 수, 사고건수, 차량대수 등 이산적인 값을 갖는 데이터로  수치적인 의미를 가지나 소수점의 형태로 표현되지 못하는 데이터를 의미
  - 연속형(Continuous Data) : 신장, 체중, 시간, 길이 등 연속적인 값을 가지고 소수점으로 표현이 가능한 데이터를 의미

더미변수란 범주형 변수에 있는 범주 각각을 컬럼으로 변경하고, 원본 컬럼의 값이 해당 범주에 속하는지 여부에 따라 1 혹은 0으로 채운 변수이다.  
pd.get_dummies(df, columns=['범주형변수'])

0을 많이 가지고 있는 행렬 = 희소행렬

**iris 데이터의 target값인 범주형 변수를 더미변수 형태로 대체**

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

In [6]:
iris = load_iris()
iris = pd.DataFrame(iris.data, columns=iris.feature_names)
iris['target'] = load_iris().target

In [7]:
iris['target'].sample(10)

36     0
55     1
3      0
63     1
117    2
85     1
90     1
147    2
88     1
68     1
Name: target, dtype: int64

In [8]:
iris['target'] = iris['target'].replace([0,1,2],['Setosa', 'Versicolour', 'Virginica'])
#iris['target'] = iris['target'].map({0:'Setosa', 1:'Versicolour', 2:'Virginica'})
iris['target']

0         Setosa
1         Setosa
2         Setosa
3         Setosa
4         Setosa
         ...
145    Virginica
146    Virginica
147    Virginica
148    Virginica
149    Virginica
Name: target, Length: 150, dtype: object

In [4]:
# 더미로 바꿔서 작업
iris_dummy = pd.get_dummies(iris, columns=['target'])
iris_dummy

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),target_Setosa,target_Versicolour,target_Virginica
0,5.1,3.5,1.4,0.2,1,0,0
1,4.9,3.0,1.4,0.2,1,0,0
2,4.7,3.2,1.3,0.2,1,0,0
3,4.6,3.1,1.5,0.2,1,0,0
4,5.0,3.6,1.4,0.2,1,0,0
...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,0,0,1
146,6.3,2.5,5.0,1.9,0,0,1
147,6.5,3.0,5.2,2.0,0,0,1
148,6.2,3.4,5.4,2.3,0,0,1
149,5.9,3.0,5.1,1.8,0,0,1